---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}


library(tidyverse)
library(plotly)


rdn = "C:/Users/McMillanAn/OneDrive - MWLR/Rarotonga/"

subdirs = list.dirs(rdn)




```

```{r}
read_spec = function(ffn){
  
  # ffn = "C:/Users/McMillanAn/OneDrive - MWLR/Rarotonga/tulip_spectra_Sep_2016/green/Reflection_16-13-23-279.txt"
  D = read_delim(ffn, col_names = F,skip = 16,delim = "\t")
  names(D) <- c("wavelength", "refl")
  
  HDR_INFO=read_lines(ffn,n_max=3)
  
  g = ggplot(D, aes("wavelength", "refl")) + geom_point() + geom_line()
  
  
  return(list(D,HDR_INFO,g))
  
}


dn1 = "C:/Users/McMillanAn/OneDrive - MWLR/Rarotonga/tulip_spectra_Sep_2016/green/"
dn2 = "C:/Users/McMillanAn/OneDrive - MWLR/Rarotonga/tulip_spectra_Sep_2016/leaves/"
dn3 = "C:/Users/McMillanAn/OneDrive - MWLR/Rarotonga/tulip_spectra_Sep_2016/red/"
dn4 = "C:/Users/McMillanAn/OneDrive - MWLR/Rarotonga/tulip_spectra_Sep_2016/orange/"

dn_list = c(dn1,dn2,dn3,dn4)


```



```{r}


for (idn in 1:length(dn_list)){
  
  dn = dn_list[idn]
  
  
  fls = list.files(dn, full.names = T, pattern = ".txt$")
  
  FLS = lapply(fls, read_spec)
  
  for (i in 1:length(FLS)){
    
    # i=1
    print("======================================")
    print(i)
    print("======================================")
    data = FLS[[i]][[1]] %>% 
      mutate(
        wavelength = as.numeric(wavelength),
        refl = as.numeric(refl),
        id = FLS[[i]][[2]][1], 
        Date_Info =  FLS[[i]][[2]][2]
      )
    
    if (i==1){
      alldata = data
    }else{
      alldata = bind_rows(alldata,data)
    }
    
  }
  curr_dn = basename(dn)
  
  alldata = alldata %>% 
    mutate(
      
      id2 = str_extract(id,"\\d{2}\\-\\d{2}\\-\\d{2}\\-\\d{3}"),
      YEAR   = str_extract(Date_Info, "\\d{4}$"),
      DOW_MON_DOM   = str_extract(Date_Info,  "\\s[:alpha:]{3}\\s[:alpha:]{3}\\s\\d{2}"),
      TIME = str_extract(Date_Info,  "\\d{2}\\:\\d{2}\\:\\d{2}"),
      DATESTR = paste0(substr(DOW_MON_DOM,10,11),"-",substr(DOW_MON_DOM,6,8),"-", YEAR," ",TIME),
      DATETIME = as.POSIXct(DATESTR, format = "%d-%b-%Y %H:%M:%S"),
      plant_color = curr_dn ) %>% 
    select(DATETIME, wavelength, refl, id2, plant_color)
  
  g = ggplot(alldata, aes(wavelength, refl)) + geom_line() + facet_wrap(~id2) + ylim(c(0, 100))
  g = g + ggtitle(paste("Tulip Spectra -" ,basename(dn)))
  g
  
  ggsave( paste0(dn, "plots.png"),g)
  
  
  str_extract("\rDate: Tue Sep 06 16:13:13 FJT 2016", "\\s[:alpha:]{3}\\s")
  
  YEAR   = str_extract("\rDate: Tue Sep 06 16:13:13 FJT 2016", "\\d{4}$")
  DOW_MON_DOM = str_extract("\rDate: Tue Sep 06 16:13:13 FJT 2016", "\\s[:alpha:]{3}\\s[:alpha:]{3}\\s\\d{2}")
  DATESTR = paste0(substr(DOW_MON_DOM,10,11),"-",substr(DOW_MON_DOM,6,8),"-", YEAR)
  
  
  if (idn==1){
    
    
    collated_spectra = alldata
  }else{
    collated_spectra = bind_rows(collated_spectra,alldata)
  }
  
}



collated_spectra_ffn = paste0(rdn, "collated_spectra.csv")
write_csv(collated_spectra, collated_spectra_ffn)


#summarise spectra
collated_spectra_smy = collated_spectra %>% 
  filter(refl >=0 & refl <=100) %>% 
  mutate(PLANT_COMPONENT = 
           case_when(
             plant_color == "leaves" ~ "LEAVES",
             plant_color == "red" ~ "RED BITS",
             plant_color == "green" ~ "GREEN BITS",
             plant_color == "orange" ~ "ORANGE BITS"
           )) %>% 
  group_by(PLANT_COMPONENT, wavelength) %>% 
  summarise(
    refl_avg = mean(refl),
    refl_sd = sd(refl)) %>% 
  mutate(
    refl_plus_1sd = refl_avg + refl_sd,
    refl_minus_1sd = refl_avg - refl_sd,
  )


collated_spectra_smy$plant_color = factor(collated_spectra$plant_color, levels = c("green","leaves","orange","red"))

colmap = c("green"="green","leaves"="darkgreen", "orange"="orange", "red" = "red")

    
g = ggplot(collated_spectra_smy) +geom_ribbon(aes(wavelength, ymin = refl_minus_1sd, ymax = refl_plus_1sd ), fill = "cyan", alpha = .5) + facet_wrap(~PLANT_COMPONENT)
g = g  + geom_line(aes(wavelength , refl_avg), size = 1)
g = g + scale_color_manual(values = c("green", "darkgreen","orange","red"))
g

ggsave(paste0(rdn,"spectra_facet_plot.png"), g)


g = ggplot(collated_spectra_smy) +geom_line(aes(wavelength , refl_avg, color = PLANT_COMPONENT), size = 1) 
g = g + scale_color_manual(values = c("green", "darkgreen","orange","red"))
g


ggsave(paste0(rdn,"spectra_single_plot.png"), g)









# FLS[[1]][[1]]
# FLS[[1]][[2]]


```

